version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tomas
      POSTGRES_PASSWORD: bluebird48
      POSTGRES_DB: adaptacija
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://tomas:bluebird48@db:5432/adaptacija
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm start
      "

volumes:
  postgres-data:
